/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Travis' at '12/28/16 9:35 AM' with Gradle 2.14.1
 *
 * @author Travis, @date 12/28/16 9:35 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
